#!/usr/bin/env bash

DRIVEPATH_DEFAULT="/mnt/gayming/school/win11.qcow2"
WIN11_DEFAULT="/mnt/gayming/school/win11.iso"
WIN11="${WIN11:=$WIN11_DEFAULT}"
DRIVEPATH="${DRIVEPATH:=$DRIVEPATH_DEFAULT}"

QEMU_CPU_OPT="host,hv_relaxed,hv_frequencies,hv_vpindex,hv_ipi,hv_tlbflush,hv_spinlocks=0x1fff,hv_synic,hv_runtime,hv_time,hv_stimer,hv_vapic"

set -xe

if ! [ -f "$DRIVEPATH" ]; then
 qemu-img create -f qcow2 "$DRIVEPATH" 50G
fi
qemu-system-x86_64 -M q35,usb=on,acpi=on,hpet=off -m 8G \
                  -cpu "$QEMU_CPU_OPT" \
                  -vga qxl -device virtio-serial-pci \
                  -spice port=5930,disable-ticketing=on \
                  -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 \
                  -chardev spicevmc,id=spicechannel0,name=vdagent -display spice-app \
                  -smp cores=4 -accel kvm -drive file="$DRIVEPATH" \
                  -device usb-tablet \
                  -nic user,model=e1000 -monitor stdio